In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
zeros_arr=np.zeros((3,3),dtype=int)
print(zeros_arr)
ones_arr=np.ones((2,2),dtype=int)
print(ones_arr)
arange_arr=np.arange(10)
print(arange_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#array manipulation
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)
sliced_arr=arr[2:4]
print(sliced_arr)

[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b=a.T
print(b)

[1 2 3 4 5 6 7 8]


In [ ]:
b=np.split(a,4)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)

[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [ ]:
data=np.loadtxt("/content/drive/MyDrive/dataset/data.txt.txt",dtype=int)
d=np.savetxt("/content/date.txt",data)
print(d)
print(data)

None
[1 2 3 4 5 6]


NameError: name 'o' is not defined

In [ ]:
m=np.savetxt("/content/arange.txt",ar_arr)

In [ ]:
a=np.random.rand()
print(a)

0.777681772943628


In [ ]:
b=np.random.randint(0,2)
print(b)

1


In [ ]:
a=np.array([[1,2],[3,4]])
print(a.shape)


(2, 2)


In [ ]:
ar_arr=np.arange(0,1000,5)
print(ar_arr)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [ ]:
a=np.linspace(0.8,2,5)
print(a)

[0.8 1.1 1.4 1.7 2. ]


In [ ]:
a=np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
a=np.arange(29).reshape(2,3,5)
print(a)

ValueError: cannot reshape array of size 29 into shape (2,3,5)

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a*b)

[[ 5 12]
 [21 32]]


In [ ]:
print(a@b)

[[19 22]
 [43 50]]


In [ ]:
d=np.dot(a,b)
print(d)

[[19 22]
 [43 50]]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
print(a.sum())
print(a.sum(axis=0))

[[1 1 1]
 [1 1 1]]
6
[2 2 2]


In [ ]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a)
print(a.max(axis=0))

[[1 1 1]
 [1 1 1]]
[1 1 1]


In [ ]:
c=np.ceil(np.random.random((2,12)))
print(c)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
from numpy import random
a=np.array([[12,4],[7,8],[99,45]])
print(a.cumsum(axis=1))
print(a.cumsum(axis=0))


[[ 12  16]
 [  7  15]
 [ 99 144]]
[[ 12   4]
 [ 19  12]
 [118  57]]


In [ ]:
a=np.array([2,3,5,6])
print(a.cumsum())

[ 2  5 10 16]


In [ ]:
a=np.array([1,2,3,4,5,6])
b=a.resize(3,2)
print(a.shape)


(3, 2)


In [ ]:
a=np.array([1,2,3,4,5,6])
a.resize(2,3)
b=np.array([11,12,13,14,15,16])
b.resize(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print(np.dstack(a))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
a1=np.eye(4)
print(a1)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a1=np.full((2,2),3)
print(a1)
print(a1.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


number of rows become number of groups
column become row
group become column

In [ ]:
a=np.array([1.3,2.7,3.4,2.5],dtype=float)
c=np.rint(a)
print(c)


[1. 3. 3. 2.]


In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([5,6,7,8,9])
print(np.true_divide(x,y))

[0.2        0.33333333 0.42857143 0.5        0.55555556]


In [ ]:
a=np.array([1,1,2,2,3,3,4,4])
print(np.unique(a))

[1 2 3 4]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7]]),([[8,9,10]])
c=np.union1d(a,b)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=np.intersect1d(a,b)
print(c)

[5 6]


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,6,7],[8,9,10]])
c=np.setdiff1d(a,b)
print(c)

[1 2 3 4]


In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
x=np.sin(0)
print(x)

0.0


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.mod(a,b)
print(c)


[10  0  0  0  0 10]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)


(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divide(a,b)
print(c)


[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.matmul(a,b))

4251


In [ ]:
from numpy import random
x=random.normal(size=(2,3))
print(x)

[[-0.42722683 -0.25503261  0.18117919]
 [ 0.53244886 -1.47144204  0.2980439 ]]


In [ ]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[0.6588934  6.17087272 1.88725341]
 [0.91663513 0.94085205 1.45915353]]


In [ ]:
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[ 4  5  4 10  8  4  6  5  6  5]


In [ ]:
x=random.poisson(lam=2,size=10)
print(x)

[2 0 3 1 0 1 1 1 3 3]


In [ ]:
x=random.choice([4,6,7,5])
print(x)

6


In [ ]:
x=random.choice([3,5],p=[0.2,0.8],size=(3,5))
print(x)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 3]]


In [ ]:
x=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(x)

[[3 3 5 5 5]
 [3 5 5 3 5]
 [5 3 5 3 3]]


In [ ]:
import pandas as pd
 a=["jwalitha",'ramya','durga','lahari','sunny','dhanush']
r=pd.Series(a,index=[67,43,44,89,34,45])
print(r)

IndentationError: unexpected indent (<ipython-input-53-71dfc5acbc30>, line 2)